AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  pdftotxt:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: PDFtoTXT/src/  # Correct path from the root of the repository
      Description: ''
      MemorySize: 512
      Timeout: 900
      Role: 'arn:aws:iam::153648754796:role/lambda_s3'
      Environment:
        Variables:
          TARGET_BUCKET: dev-gl-inter-store

