version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
  build:
    commands:
      - echo "Current working directory:"
      - pwd  # Check the working directory
      - echo "Listing files in the current directory:"
      - ls -R  # List all files to verify the folder structure
      - aws cloudformation package --template-file PDFtoTXT/cloudformation/pdftotxt.yaml --s3-bucket dev-artifacts-bucket-gl --output-template-file lambdaoutput.yaml
artifacts:
  type: zip
  files:
    - PDFtoTXT/cloudformation/pdftotxt.yaml
    - lambdaoutput.yaml
