version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
  build:
    commands:
      - echo "Current working directory:"
      - pwd  # This will print the current working directory in CodeBuild
      - aws cloudformation package --template-file PDFtoTXT/cloudformation/pdftotxt.yaml --s3-bucket dev-artifacts-bucket-gl --output-template-file lambdaoutput.yaml
artifacts:
  type: zip
  files:
    - PDFtoTXT/cloudformation/pdftotxt.yaml
    - lambdaoutput.yaml
